version: "3"
services:
  app_caixa:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    environment:
      - APP_PORT=3000
      - JWT_SECRET=secret
      - DATABASE_URL=mysql://root:123456@database:3306/caixa
      - DB_USER=root
      - DB_PASS=123456
      - DB_HOST=database
      - DB_PORT=3306
      
  frontend_caixa:
    build:
      context: ./front-end/loja
      dockerfile: Dockerfile
    ports:
      - 3001:3001
      
  database:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=123456